# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Xinwei Zhang"

# A description of your site for meta tag, search engine results.
description: "Welcome to my personal website! Here, I share my thoughts, ideas, and projects related to statistics, probability, machine learning, and more. "


# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://xinweizhang.github.io"

# Favicon
favicon: images/favicon-X.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Publications
    url: /publications
  - text: By Topics
    url: /tags

#  - text: Style Guide
#    url: /style-guide/
#  - text: Download
#    url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy;2023 Xinwei Zhang. Powered by <a href=\"https://jekyllrb.com/\">Jekyll</a> and the <a href=\"https://jekyllthemes.io/theme/scriptor\">Scriptor Jekyll theme</a> by <a href=\"https://www.justgoodthemes.com/\">JustGoodThemes</a>. Licensed under <a href=\"https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme/blob/master/LICENSE.md\">MIT License</a>."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

staticman_url: https://staticman-xinweizhang.herokuapp.com/v3/entry/github/XinweiZhang/XinweiZhang.github.io/staticman/comments
